[package]
name = "deck_creator_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
lazy_static = "1.4.0"
regex = "1.8.4"
serde_json = "1.0.96"
walkdir = "2.3.3"
